nav:
  logo: img/icon.jpg #image 填入連結
  display_title: true # 是否顯示網站標題
  fixed: false # fixed navigation bar
subtitle: # 主頁subtitle
  enable: true
  # Typewriter Effect (打字效果)
  effect: true
  startDelay: 300 # time before typing starts in milliseconds
  typeSpeed: 150 # type speed in milliseconds
  backSpeed: 50 # backspacing speed in milliseconds
  # loop (循環打字)
  loop: true
  # source 調用第三方服務
  # source: false 關閉調用
  # source: 1  調用一言網的一句話（簡體） https://hitokoto.cn/
  # source: 2  調用一句網（簡體） http://yijuzhan.com/
  # source: 3  調用今日詩詞（簡體） https://www.jinrishici.com/
  # subtitle 會先顯示 source , 再顯示 sub 的內容
  source: false
  # 如果關閉打字效果，subtitle 只會顯示 sub 的第一行文字
  sub:
    - 看看下北澤大天使
    - 好可愛
menu:
  首頁: / || fas fa-home
  時間軸: /archives/ || fas fa-archive
  標籤: /tags/ || fas fa-tags
  分類: /categories/ || fas fa-folder-open
  # 清單||fa fa-heartbeat:
  #   音樂: /music/ || fas fa-music
  #   照片: /Gallery/ || fas fa-images
  #   電影: /movies/ || fas fa-video
  友鏈: /link/ || fas fa-link
  關於: /about/ || fas fa-heart
aside: # 首頁的側欄
  enable: true
  hide: false
  button: false
  mobile: true # display on mobile
  position: right # left or right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description: 頭像的描述
    button:
      enable: false
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/xxxxxx
  card_announcement:
    enable: true
    content: 暫無公告
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
    sort_order: 1 # Don't modify the setting unless you know how it works
  card_categories:
    enable: true
    limit: 2 # if set 0 will show all
    expand: true # none/true/false
    sort_order: 2 # Don't modify the setting unless you know how it works
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: false
    orderby: random # Order of tags, random/name/length
    order: 1 # Sort of order. 1, asc for ascending; -1, desc for descending
    sort_order: 3 # Don't modify the setting unless you know how it works
  card_archives:
    enable: false
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: # Don't modify the setting unless you know how it works
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: 5 # Don't modify the setting unless you know how it works
busuanzi: # 網站訪問人數
  site_uv: true # 本佔總訪問量
  site_pv: true # 本站總訪客數
  page_pv: true # 本文總閱讀量 (顯示在文章的top img)
runtimeshow: # 計算開站日期
  enable: true
  publish_date: 5/16/2023 00:00:00
newest_comments: # 最新評論
  enable: false
  sort_order: 4 # Don't modify the setting unless you know how it works
  limit: 6
  storage: 10 # 評論站存時間
  avatar: true
highlight_theme: darker
highlight_copy: true
highlight_shrink: false # true時代碼框不展開，需點擊 '>' 打開
code_word_wrap: false # 自動換行，防止code有橫向滾動條
highlight_height_limit: 200 # 200px的code高度限制，超過，則必須展開才看的到全部
social:
  fab fa-github: https://github.com/a40693651 || Github || "#hdhfbb" # 支持 font-awesome v6 圖標.
  fas fa-envelope: mailto:xxxxxx@gmail.com || Email || "#000000" # 圖標名：url || 描述性文字 || color
avatar: # 頭像
  img: /img/icon.jpg
  effect: false # 頭像會一直轉圈
default_top_img: transparent
cover:
  index_enable: true # 主頁是否顯示文章封面
  aside_enable: true # 側欄是否顯示文章封面
  archives_enable: true # 歸檔是否顯示文章封面
  # 封面顯示的位置
  # 三個值可配置 left , right , both
  position: both
  # 當沒有設置cover時，默認的封面顯示
  default_cover: img/default_cover.png
post_meta:
  page:
    date_type: both # created or updated or both 主頁文章日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 主頁是否顯示分類
    tags: true # true or false 主頁是否顯示標籤
    label: true # true or false 顯示描述性文字
  post:
    date_type: both # created or updated or both 文章頁日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 文章頁是否顯示分類
    tags: true # true or false 文章頁是否顯示標籤
    label: true # true or false 顯示描述性文字
index_post_content:
  method: 2 # 優先顯示description,若無，則顯示自動節選
  length: 100 # if you set method to 2 or 3, the length need to config
copy:
  enable: true
  copyright:
    enable: true
    limit_count: 50
post_copyright:
  enable: true
  decode: true
  author_href: https://github.com/a40693651
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/
toc: # 側邊的目錄欄 Table of Contents
  post: true
  page: true
  number: true
  expand: false # 蛤
  style_simple: false # for post
  scroll_percent: true
related_post:
  enable: true
  limit: 3 # 顯示推薦文章數目
  date_type: created # or created or updated 文章日期顯示創建日或者更新日
# post_pagination (分頁)
# value: 1 || 2 || false
# 1: The 'next post' will link to old post
# 2: The 'next post' will link to new post
# false: disable pagination
post_pagination: 2
readmode: true # 閱讀模式 只留文章
darkmode:
  enable: true
  # dark mode和 light mode切換按鈕
  button: true
  autoChangeMode: false
  # Set the light mode time. The value is between 0 and 24. If not set, the default value is 6 and 18
  start: # 8
  end: # 22
rightside_scroll_percent: true # 右側藍色小按鍵的文章百分比
error_404:
  enable: true
  subtitle: "頁面沒有找到"
  background: 
# fancybox http://fancyapps.com/fancybox/3/
fancybox: true # 圖片放大
# Local search
local_search:
  enable: true
  # Preload the search data when the page loads.
  preload: false
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: false
  CDN:
mathjax:
  enable: true
  # true 表示每一頁都加載mathjax.js
  # false 需要時加載，須在使用的Markdown Front-matter 加上 mathjax: true
  per_page: true
kramed: # 用來渲染mathjax的renderer
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true
comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo
  use: Waline
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: false
  count: true # Display comment count in top_img
  card_post_count: false # Display comment count in Home Page
waline:
  serverURL: https://waline-blog-jl6kt9rpr-a40693651.vercel.app/ # Waline server address url
  bg: # waline background
  pageview: false
  option:
background: url(/img/103304065.jpg)
# footer是否顯示圖片背景(與top_img一致)
footer_bg: true
beautify: # 頁面美化，改善title, li 之前的icon，
  enable: true
  field: site # site/post
  title-prefix-icon: '\f0c1' # fontawesome的icon的Unicode數
  title-prefix-icon-color: "#F47466"
wordcount:
  enable: true
  post_wordcount: true
  min2read: true # 預測閱讀時長
  total_wordcount: true
categoryBar: # 置頂category
  enable: true # 开关
  priority: 2 #过滤器优先权
  enable_page: / # 应用页面
  layout: # 挂载容器类型
    type: id
    name: recent-posts
    index: 0
  column: odd # odd：3列 | even：4列
  row: 2 #显示行数，默认两行，超过行数切换为滚动显示
  message:
    - descr:
      cover:
  custom_css: https://npm.elemecdn.com/hexo-butterfly-categories-card@1.0.0/lib/categorybar.css

inject:
  head:
    - <link rel="stylesheet" href="/css/transpancy.css">
    - <link rel="stylesheet" href="/css/cover_position.css">
    - <link  rel="stylesheet" href="https//fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@1,300&display=swap">
  bottom:
font:
  global-font-size: 16px
  code-font-size:
  font-family:
  code-font-family:
